name: "\U0001F41E Bug report/ 反馈Bug "
description: Report an issue with 52abp /报告一个52abp的问题
labels: [pending triage]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写此错误报告！ Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: 请描述下错误 Describe the bug
      description: 对错误是什么的清晰简洁的描述。如果您打算为此问题提交 PR，请在说明中告诉我们。谢谢！
      placeholder: 需要您提供使用ABP的版本号、报错的截图信息及内容描述。
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.

        1. Run `vite` or `vite build` with the `--debug` flag.
        2. Provide the error log here.
      render: shell
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: 遵守 [52ABP社区行为准则](https://github.com/vitejs/vite/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: 阅读 [贡献指南](https://github.com/vitejs/vite/blob/main/CONTRIBUTING.md).
          required: true
        - label: 阅读开发 [文档](https://vitejs.dev/guide).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/vitejs/vite/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
# 以上参考的是 https://vitejs.dev/guide
